### PR TITLE
Misc. examples updates

### PR DESCRIPTION
**Pull request by tasleson**
* `README.md` add blurb about building examples
* fmt/clippy/small change to `examples/simple.rs`

### CODE REVIEW

**Comment by cberner** [comment]
Looks like there are some compilation failures. I think those types are platform dependent.

**Comment by tasleson** [comment]
> Looks like there are some compilation failures. I think those types are platform dependent.

I'll take a look at it next week, thanks!

**Comment by tasleson** [comment]
> > Looks like there are some compilation failures. I think those types are platform dependent.
> 
> I'll take a look at it next week, thanks!

Sorry I didn't get back to this, I'm dealing with an illness.

**Comment by cberner** [comment]
No worries. I think I made most of the same changes in my PR, but if I missed anything feel free to send a new PR. I hope you feel better soon!

**Pull request closed without merging**
